### ISSUE TITLE
Feature Request: state_not condition

### ISSUE THREAD

**Issue by joshtbernstein** [bratanon/lovelace-conditional-entity-row#1]
Would love to see the ability to use state_not:

```
- entity: sensor.hacs
  type: custom:conditional-entity-row
  condition:
    - entity: sensor.hacs
      state_not: '0'
```

**Comment by Nornode** [comment]
Yes, this would be awesome and actually why I just installed this!

My Usecase is:
```
    type: custom:conditional-entity-row
      condition:
        entity: switch.sonoff_basic_relay
        state_not: 'unavailable'
```
This is for an entity that is intentionally not plugged in for a long time.
